---
# The IP address or hostname 
# of your favorite MQTT broker
mqttBroker: your.own.broker
brokerPort: 1883

# Enter credetials if needed
userName: 
password:

# Listening topic
topic: tibber/#

# Topics for publishing
pubTopic: pulse/meter
pubStatus: pulse/status
pubNotice: pulse/notice

# ElWiz event messages
willMessage: ElWiz has left the building
greetMessage: ElWiz is singing

# Tibber Pulse event messages
onlineMessage: Pulse is talking
offlineMessage: Pulse is quiet

# Debug mode at startup
DEBUG: true

# Republish mode at startup
REPUBLISH: false
